on:
  push:


name: Check

permissions: write-all

jobs:
  build:
    name: Create Artifact
    runs-on: ubuntu-latest
    steps:
    - name:  
    id: create_artifact
    uses: actions/upload-artifact@v4
    with:
      name: my-artifact
      path: path/to/artifact/
